### ISSUE TITLE
The WindowManager is blocking any text input and even Back button on the background Acitivty. 

### ISSUE THREAD

**Issue by PeterSterba** [loregr/LGSnackbar#1]
To fix this, please change in 'LGSnackbarPresenter#createDefaultLayoutParams()'  line 117

 `layoutParams.flags = WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL | WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE;`

**Comment by loregr** [comment]
Fixed here: https://github.com/loregr/LGSnackbar/commit/af3516bfd246fa921f46f44b0c9b23396bf71111

Thanks
