### ISSUE TITLE
Thanks for this lib.

### ISSUE THREAD

**Issue by Rainer-Lang** [loregr/LGSnackbar#4]
How could I use this SnackBar with a CoordinatorLayout - for moving a FAB, ....

**Comment by loregr** [comment]
Since the snackbar is drawn on top o the window, you need to implement a custom behaviour for your fab. It can't be used with CoordinatorLayout.

**Comment by Rainer-Lang** [comment]
Is there an example?

**Comment by loregr** [comment]
There is no example since the implementation is strongly coupled with personal needs of each dev. But I'll probably make some refactoring to allow the use of coordinator layout. Thanks for bringing this up.
